export enum PDF_TYPES {
  PRE_CEREMONY_TIMELINE = 'PRE_CEREMONY_TIMELINE',
  CEREMONY_TIMELINE = 'CEREMONY_TIMELINE',
  RECEPTION_TIMELINE = 'RECEPTION_TIMELINE',
  WEDDING_PARTY_TIMELINE = 'WEDDING_PARTY_TIMELINE',
  VENDORS_TIMELINE = 'VENDORS_TIMELINE',
  LOCATIONS_TIMELINE = 'LOCATIONS_TIMELINE',
}
