export const TRADE_KEYS = {
  SECURITY_DESCRIPTION_KEY_KEY: 'DESCR',
  SECURITY_TYPE_KEY: 'SECURITYTYPE',
  SECURITY_ID_KEY: 'SECURITYID',
  ISSUER_KEY: 'ISSUERNAME',
  COUPON_KEY: 'CPNRT',
  MATURITY_KEY: 'DTMATURITY',
  PAR_KEY: 'FACEAMT',
  SETTLE_DATE_KEY: 'DTSETTLE',
  PRICE_KEY: 'SETTLEPRC',
  YIELD_KEY: 'SETTLEYLD',
  EXCLUDE_HOLIDAY_KEY: 'INTHOLIDAYRULE',
  AFTER_TAX_CALCS_KEY: 'AFTERTAXCALCSYN',

  RATE_RESET_FREQUENCY_KEY: 'RESETPERIODICITY',
  USE_FIXING_CURVE_KEY: 'USEFIXINGCURVEYN',

  LAST_FACTOR_DATE_KEY: 'DTPASSFACTOR',
  WEGHTED_AVG_MATURITY_KEY: 'PASSWARM',
  FACTOR_KEY: 'PASSFACTOR',

  PRE_PAY_MADEL_KEY: 'PASSMODEL',
  PRE_PAY_SPEED_KEY: 'PREPAYSPEED',

  INDEX_RATIO_AT_SETTLE_KEY: 'IDXRATIOATSETTLE',
  INFLATION_RATE_KEY: 'INFLATIONRT',
  MATURITY_ADJUSTED_KEY: 'ADJUSTMATURITYYN',
  STATE_OF_ISSUE_KEY: 'STATEOFISSUE',
  STATE_OF_RESIDENCE_KEY: 'STATEOFRESIDENCE ',
  FED_TAX_RATE_KEY: 'TAXRATEFEDINCOME',
  STATE_TAX_RATE_KEY: 'TAXRATESTATEINCOME',

  CALL_DATES_KEY: 'DTCALL',
  CALL_PRICES_KEY: 'CALLPRC',

  SINK_DATE_KEY: 'DTSINK',
  SNK_AMOUNT_KEY: 'SINKAMT',
  SINK_PRICE_KEY: 'SINKPRC',

  PAR_CURVE_KEY: 'FIXINGPARYN',
  FIXING_MATURITY_MOS_KEY: 'FIXINGMATLEN',
  FIXING_RATE_KEY: 'FIXINGRT',

  SPOT_CURVE_KEY: 'DISCRTPARYN',
  DISCOUNT_MATURITY_MOS_KEY: 'DISCMATLEN',
  DISCOUNT_RATE_KEY: 'DISCRT',
};
