export const PRIMARY_COUPLE_ID_KEY = 'PRIMARY_COUPLE_ID';
export const SECONDARY_COUPLE_ID_KEY = 'SECONDARY_COUPLE_ID';

export const USER_EMAIL_KEY = 'USER_EMAIL';

export const USER_ID_KEY = 'USER_ID';
export const USER_SUBSCRIPTION_TYPE_KEY = 'USER_SUBSCRIPTION_TYPE';
export const USER_VERSION_KEY = 'USER_VERSION';

export const NEW_ACTIVE_ONBOARDING_STEP_KEY = 'NEW_ACTIVE_ONBOARDING_STEP_KEY';
export const NEW_ONBOARDING_STEPS_KEYS = {
  OFFSET: 'OFFSET',
  FIRST_LOOK: 'FIRST_LOOK',
  FIRST_LOOK_LOCATION: 'FIRST_LOOK_LOCATION',
  WEDDING_TYPE: 'WEDDING_TYPE',
  WEDDING_DATE: 'WEDDING_DATE',
  WEDDING_TIME: 'WEDDING_TIME',
  CEREMONY_LOCATION_SELECTION: 'CEREMONY_LOCATION_SELECTION',

  WELCOME: 'WELCOME',
  COUPLE_TYPE_SELECTION: 'COUPLE_TYPE_SELECTION',
  CEREMONY_SELECTION: 'CEREMONY_SELECTION',
  CEREMONY_TIME_SELECTION: 'CEREMONY_TIME_SELECTION',
  RECEPTION: 'RECEPTION',
  RECEPTION_LOCATION: 'RECEPTION_LOCATION',
  PRIMARY_HAIR_AND_MAKEUP: 'PRIMARY_HAIR_AND_MAKEUP',
  PRIMARY_GETTING_DRESSED: 'PRIMARY_GETTING_DRESSED',
  SECONDARY_HAIR_AND_MAKEUP: 'SECONDARY_HAIR_AND_MAKEUP',
  SECONDARY_GETTING_DRESSED: 'SECONDARY_GETTING_DRESSED',
  PERSONAL_INFO_OR_FIRST_LOOK_NEW_PLACE: 'PERSONAL_INFO_OR_FIRST_LOOK_NEW_PLACE',
  PERSONAL_INFO: 'PERSONAL_INFO',
};
