import { NEW_ONBOARDING_STEPS_KEYS, PRIMARY_COUPLE_ID_KEY, SECONDARY_COUPLE_ID_KEY } from 'constants/localStorage';

export function clearOnboardingAndResetTimelineData() {
  localStorage.removeItem(NEW_ONBOARDING_STEPS_KEYS.CEREMONY_LOCATION_SELECTION);
  localStorage.removeItem(NEW_ONBOARDING_STEPS_KEYS.OFFSET);
  localStorage.removeItem(NEW_ONBOARDING_STEPS_KEYS.WEDDING_TIME);
  localStorage.removeItem(NEW_ONBOARDING_STEPS_KEYS.WEDDING_DATE);
  localStorage.removeItem(NEW_ONBOARDING_STEPS_KEYS.FIRST_LOOK);
  localStorage.removeItem(NEW_ONBOARDING_STEPS_KEYS.FIRST_LOOK_LOCATION);
  localStorage.removeItem(NEW_ONBOARDING_STEPS_KEYS.PRIMARY_GETTING_DRESSED);
  localStorage.removeItem(NEW_ONBOARDING_STEPS_KEYS.PRIMARY_HAIR_AND_MAKEUP);
  localStorage.removeItem(NEW_ONBOARDING_STEPS_KEYS.RECEPTION_LOCATION);
  localStorage.removeItem(NEW_ONBOARDING_STEPS_KEYS.SECONDARY_HAIR_AND_MAKEUP);
  localStorage.removeItem(NEW_ONBOARDING_STEPS_KEYS.SECONDARY_GETTING_DRESSED);
  localStorage.removeItem(PRIMARY_COUPLE_ID_KEY);
  localStorage.removeItem(SECONDARY_COUPLE_ID_KEY);
}
